### ISSUE TITLE
Error: Could not retrieve the URL for the websocket.

### ISSUE THREAD

**Issue by benj-red** [WatchBeam/interactive-unity-plugin#1]
Whenever Beam.GoInteractive() gets called, only errors return, "Error: Could not retrieve the URL for the websocket." followed by, "Error: Failed to get a new short code for authentication."

I've followed all the instructions in the "Getting Started" tutorial and all of the "Troubleshooting guide". The same errors occur whether I am testing my own scene, or any of the "Examples" scenes provided with the plugin. Here are the full texts of the errors:

Error: Could not retrieve the URL for the websocket.
UnityEngine.Debug:Log(Object)
Xbox.Services.Beam.BeamManager:Log(String, BeamLoggingLevel) (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:3079)
Xbox.Services.Beam.BeamManager:LogError(String) (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:3068)
Xbox.Services.Beam.BeamManager:InitiateConnection() (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:273)
Xbox.Services.Beam.BeamManager:Initialize(Boolean) (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:221)
Microsoft.Beam:BackgroundWorkerDoWork(Object, DoWorkEventArgs) (at Assets/Beam/Source/Scripts/Beam.cs:683)
System.ComponentModel.BackgroundWorker:ProcessWorker(Object, AsyncOperation, SendOrPostCallback)

Error: Failed to get a new short code for authentication.
UnityEngine.Debug:Log(Object)
Xbox.Services.Beam.BeamManager:Log(String, BeamLoggingLevel) (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:3079)
Xbox.Services.Beam.BeamManager:LogError(String) (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:3068)
Xbox.Services.Beam.BeamManager:RefreshShortCode() (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:678)
Xbox.Services.Beam.BeamManager:InitiateConnection() (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:291)
Xbox.Services.Beam.BeamManager:Initialize(Boolean) (at E:/GIT/Repos/Microsoft/xbox-live-beam-api-csharp/Source/api/BeamManager.cs:221)
Microsoft.Beam:BackgroundWorkerDoWork(Object, DoWorkEventArgs) (at Assets/Beam/Source/Scripts/Beam.cs:683)
System.ComponentModel.BackgroundWorker:ProcessWorker(Object, AsyncOperation, SendOrPostCallback)

**Comment by payzer** [comment]
Are you running it in the Unity Editor?

**Comment by benj-red** [comment]
Yes, I tested this first in the Unity Editor.

I also tried making a Windows build, but that did not seem to work either.

**Comment by payzer** [comment]
Thank you. I am able to repro this on my end now as well. Let me check with our services developers.

**Comment by payzer** [comment]
We've investigating.

**Comment by payzer** [comment]
Update:
We have root caused the issue. Unfortunately we do not have an ETA on a fix yet. We are very, very sorry, but unfortunately for now you will only be able to use the local input simulation in the Beam Editor until we have the issue resolved.

The Beam Editor can be found by going to Beam > Open Editor.

**Comment by benj-red** [comment]
OK, thank you for the update. I'm super psyched to working with interactive 2.0, and I look forward to seeing it's full capabilities in-action! Cheers,

**Comment by payzer** [comment]
The issue is now resolved. We've verified the SDK can connect now.

Thank you so much for your patience and sorry for the delay. The team is very happy to hear you are excited about Interactive 2.0 :)

**Comment by payzer** [comment]
I wanted to respond for people still experiencing connection issues. The fix propagated to most, but not all of our endpoints. We are now propagating the fix to all of our endpoints to that the error "Error: Could not retrieve the URL for the websocket." will go away completely.
