### ISSUE TITLE
Cannot get Button by participant

### ISSUE THREAD

**Issue by payzer** [WatchBeam/interactive-unity-plugin#2]
GetButton("TheButtonName").GetButtonDown(theParticipantID) isn't working.

**Comment by payzer** [comment]
We'll get this fixed in the next release of the SDK. In the meantime, the following can be used as a workaround:

if (BeamManager.SingletonInstance.GetButton("TheButtonName").GetCountOfButtonDowns("theParticipantID") > 0) 
{ 
    // Do Stuff
}

**Comment by payzer** [comment]
We updated the releases share with a fix for this issue.

**Comment by ProbablePrime** [comment]
@payzer we should publish a new release on the github here with the fix in a changelog. See https://github.com/WatchBeam/beam-interactive-node2/releases for an example of how i do it :)

**Comment by payzer** [comment]
Thank you, I'll get that done.
