### ISSUE TITLE
BeamManager.SingletonInstance.TriggerCooldown will not work more than once.

### ISSUE THREAD

**Issue by bzaPetey** [WatchBeam/interactive-unity-plugin#4]
BeamManager.SingletonInstance.TriggerCooldown("joinGame", 3000); will trigger the cooldown the first time. After the cooldown is done, clicking it again will not trigger the cooldown again. In the debug msg, the only error I see is about the etag not matching.

**Comment by payzer** [comment]
Thank you for filing this bug. We'll investigate.

**Comment by PetePinelli** [comment]
I have had this same issue, I can confirm.  Clicking it again after the cooldown is up will still trigger the cooldown, but you have to use Beam.Button("Button").RemainingCooldown to check how much time is remaining.

I wonder if this is related to changing groups/scenes only showing once...

**Comment by payzer** [comment]
We've fixed this issue with the latest release of the plugin, available here:
https://github.com/WatchBeam/interactive-unity-plugin/releases/tag/v0.7.2-beta
