### ISSUE TITLE
Missing the Sources Folder

### ISSUE THREAD

**Issue by bzaPetey** [WatchBeam/interactive-unity-plugin#6]
when importing the unity package from here on github, I am getting the following error:

Assets/Beam/Source/Editor/BeamSettingsWindow.cs(27,5): error CS0433: The imported type `Xbox.Services.Beam.BeamLoggingLevel' is defined multiple times

Looks like the Sources folder may be missing form the latest build? If I use the content of the sources folder from a previous build. I do not get those errors.

**Comment by payzer** [comment]
Thank you, we'll investigate.

**Comment by payzer** [comment]
I wasn't able to repro. I can have a few other folks on my team give it a try. I noticed we don't have a folder called "Sources" as part of the package. We do have a "Source" folder though. Is that the one you used the contents of.

**Comment by bzaPetey** [comment]
yes, I used the content from the original release here on github. Will have to check when i get home, but i believe that is where the dll files are.

**Comment by payzer** [comment]
Thank you for double checking. The DLLs should be under Source/DLLs.

**Comment by bzaPetey** [comment]
I just downloaded the repo again and I am not seeing the sources folder with the DLLs in it.

\InteractiveSDK\Assets\Beam still has the Source.meta file from the Unity project though.

**Comment by payzer** [comment]
Here's what I'm seeing:
![image](https://cloud.githubusercontent.com/assets/6383948/26178207/e7464c28-3b11-11e7-9e93-2b375d0076fa.png)

It feels like Unity isn't downloading everything. I'll keep an eye out and see if we can get a repro of this in house. For now, I guess manually grabbing that folder until we can figure this out.

**Comment by bzaPetey** [comment]
Oh, I can not get the download from the Unity Asset Store to download as I get the error mentioned in the first post. I was referring to the repo here on github. It is missing the sources folder.

**Comment by payzer** [comment]
I'm sorry! Now I think I understand :)

When you download from this repro, download it from the releases section here: https://github.com/WatchBeam/interactive-unity-plugin/releases (click on the beam.unitypackage link)

You're right the code is missing the Source files. Is that what you meant?

**Comment by bzaPetey** [comment]
yes. Can not get the unity asset store package because the the error and can not get it from the repo because of the missing folder. :)

**Comment by payzer** [comment]
Ah, sorry for the confusion. We'll get the repo source updated, but it may be a little while due to some internal logistics. But in the meantime if you could try getting it from the releases section that will have all the files.

**Comment by payzer** [comment]
We've updated the repo with the missing files. That said, I would still encourage folks to download the beam.unitypackage from the releases tab if possible.
