### ISSUE TITLE
Cannot Change Group/Scene More Than Once

### ISSUE THREAD

**Issue by PetePinelli** [WatchBeam/interactive-unity-plugin#7]
**Description:**
When trying to change a participant's group and thus the controls and scene being displayed to them, I run into problems.  I am able to successfully change the Group and Scene the first time, however the second and all subsequent times do not appear to update the changes.

**Desired Behavior:**
When a user connects to the stream, they are automatically placed inside of the default scene.  My default scene has several buttons which will change the Group and Scene of the user and display new controls.  When any Group option button is selected, the new controls will appear.  This part works fine.  

Once in the new scene, there is a control button to return you to the default Group/Scene.  This is the part that is broken.

**Additional Info:**
When running through and trying to debug my code, I've found out that the participant's group and scene information is being updated.  What is not being updated is what Scene and controls the user actually sees on the Beam page.

My code is an absolute mess right now trying to get to the bottom of this, but I can provide a clean example if necessary.

Please reply if you've had a similar problem or may know how to help fix the issue, thanks!

**Comment by payzer** [comment]
Thank you for filing a bug. This is the same root cause as the button cooldown issue. We're investigating and will let you know when we have a fix.

**Comment by EgoAnt** [comment]
I am having similar issues, can't switch scenes for people viewing on Beam. Thought I was going a bit crazy.

**Comment by payzer** [comment]
You're not crazy :) We apologize for the bug.

**Comment by PetePinelli** [comment]
No need to apologize, it's in beta after all xD Just nice to let our minds at ease!

**Comment by payzer** [comment]
We've fixed this issue with the latest release of the plugin, available here:
https://github.com/WatchBeam/interactive-unity-plugin/releases/tag/v0.7.2-beta

**Comment by EgoAnt** [comment]
Thank you so much for the quick fix!
