### ISSUE TITLE
BeamManager.SingletonInstance.Participants

### ISSUE THREAD

**Issue by bzaPetey** [WatchBeam/interactive-unity-plugin#9]
The following code does not return the correct number of viewers. It also has multiples of some people and leaves out others.

    void Viewers()
    {
        Debug.Log("viewers in room: " + BeamManager.SingletonInstance.Participants.Count);
        foreach (BeamParticipant p in BeamManager.SingletonInstance.Participants)
            Debug.LogWarning(p.BeamUserName);
    }

**Comment by payzer** [comment]
Do you have the latest release? (https://github.com/WatchBeam/interactive-unity-plugin/releases/tag/v0.7.2-beta)

We fixed a bug that sounds similar to this one.

If you have the latest version and it still repros would it be possible to get a little more of the repro code? (we tried locally on a broadcast with 0, 1, and 2 participants and weren't able to see it get incorrect counts or user names)

**Comment by bzaPetey** [comment]
I was pretty sure that I was using the 7.2 version, but I will grab the latest version from the releases page and see if the problem still persists.

**Comment by bzaPetey** [comment]
This seems to be working in tonight stream. It is getting the correct number of viewers and there are no duplicates. I have not changed the version if the sdk that I am using though.
I will keep an eye on this as I progress in the game for beam.

**Comment by payzer** [comment]
Thank you for checking. I think we might have fixed it. I'll close the issue for now, but if it shows up again, let us know!
